import os
os.system ("clear")
print("\033[1;97m====================================================")
print("                \033[1;92m Server is off ")
print("\033[1;97m====================================================")
print("                \033[1;93m Wait for update ")
print("\033[1;97m====================================================")
print("                \033[1;96m join our Tele Channel")
print("\033[1;97m====================================================")
os.system("xdg-open https://t.me/Afghan_Tech_001")